# Generated by Django 6.0.7 on 2026-09-01 06:16

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_type', models.CharField(choices=[('looking', 'Looking for a Roommate'), ('offering', 'Offering a Room')], default='offering', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='roommates/%Y/%m/', validators=[core.validators.MaxFileSizeValidator(2048)])),
                ('room_type', models.CharField(help_text='e.g. "2 BHK Apartment", "Private Room in 3 BHK"', max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('area_locality', models.CharField(blank=True, max_length=100)),
                ('monthly_rent', models.PositiveIntegerField(help_text='Monthly rent / your share, in ₹.')),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('working_professional', 'Working Professional'), ('any', 'Any')], default='any', max_length=25)),
                ('roommates_needed', models.PositiveSmallIntegerField(default=1, help_text='How many roommates are needed (mainly relevant for "Looking for a Roommate" posts).')),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('is_active', models.BooleanField(default=True, help_text="Turn off once you've found a match — hides it from search.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
