# Generated by Django 6.0.7 on 2026-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_fix_visit_approval_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home_why_choose', 'Home — Why Choose Us'), ('home_how_it_works', 'Home — How It Works'), ('about_values', 'About — Our Values'), ('about_why_choose', 'About — Why Choose Us'), ('about_trust_steps', 'About — How Trust Works'), ('host_steps', 'Become a Host — Steps'), ('host_perks', 'Become a Host — Perks')], max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Icon name from the shared icon set, e.g. "shield-check". Leave blank for none.', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='Plain text — blank lines start a new paragraph.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
