# Generated by Django 6.0.7 on 2026-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_seed_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_photos_per_listing',
            field=models.PositiveSmallIntegerField(default=25, help_text='Maximum photos an owner can upload per listing.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_photos_to_publish',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minimum photos required before a listing can be published.'),
        ),
    ]
