# Generated by Django 6.0.7 on 2026-08-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_sitesettings_max_photos_per_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('contact', 'Contact Us'), ('become_host', 'Become a Host'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Shown in the browser tab and search results.', max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['page'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Leave blank to disable the Pixel.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX. Leave blank to disable Analytics.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Default social-share preview image for pages that don't set their own.", null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_name',
            field=models.CharField(default='Rentora', max_length=60),
        ),
    ]
