# Generated by Django 6.0.7 on 2026-08-29 03:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_seed_page_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[core.validators.MaxFileSizeValidator(512)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[core.validators.MaxFileSizeValidator(2048)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Default social-share preview image for pages that don't set their own.", null=True, upload_to='branding/', validators=[core.validators.MaxFileSizeValidator(2048)]),
        ),
    ]
