from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('tenant/dashboard/', views.tenant_home, name='tenant'),
    path('tenant/dashboard/saved/', views.saved_properties, name='tenant_saved'),
    path('tenant/dashboard/profile/', views.profile, name='tenant_profile'),
    path('tenant/dashboard/settings/', views.settings_home, name='tenant_settings'),
    path('tenant/dashboard/settings/password/', views.settings_password, name='tenant_settings_password'),
    path('tenant/dashboard/settings/notifications/', views.settings_notifications, name='tenant_settings_notifications'),
    path('tenant/dashboard/settings/privacy/', views.settings_privacy, name='tenant_settings_privacy'),
    path('tenant/dashboard/settings/language/', views.settings_language, name='tenant_settings_language'),
    path('tenant/dashboard/settings/delete/', views.settings_delete_account, name='tenant_settings_delete'),
    path('tenant/dashboard/help/', views.help_support, name='tenant_help'),

    path('owner/dashboard/', views.owner_home, name='owner'),
    path('hotel/dashboard/', views.owner_home, name='hotel'),
    path('owner/dashboard/profile/', views.owner_profile, name='owner_profile'),
    path('owner/dashboard/profile/password/', views.owner_profile_password, name='owner_profile_password'),
    path('owner/dashboard/inquiries/', views.owner_inquiries, name='owner_inquiries'),
    path('owner/dashboard/inquiries/<int:pk>/', views.owner_inquiry_detail, name='owner_inquiry_detail'),
    path('owner/dashboard/inquiries/<int:pk>/status/<str:status>/', views.owner_inquiry_set_status, name='owner_inquiry_set_status'),
    path('owner/dashboard/visits/', views.owner_visits, name='owner_visits'),
    path('owner/dashboard/visits/<int:pk>/cancel/', views.owner_visit_cancel, name='owner_visit_cancel'),
    path('owner/dashboard/visits/<int:pk>/approve/', views.owner_visit_approve, name='owner_visit_approve'),
    path('owner/dashboard/visits/<int:pk>/decline/', views.owner_visit_decline, name='owner_visit_decline'),
    path('owner/dashboard/visits/<int:pk>/complete/', views.owner_visit_complete, name='owner_visit_complete'),
    path('owner/dashboard/bookings/', views.owner_bookings, name='owner_bookings'),
    path('owner/dashboard/bookings/<int:pk>/confirm/', views.owner_booking_confirm, name='owner_booking_confirm'),
    path('owner/dashboard/bookings/<int:pk>/decline/', views.owner_booking_decline, name='owner_booking_decline'),
    path('owner/dashboard/settings/', views.owner_settings_home, name='owner_settings'),
    path('owner/dashboard/settings/password/', views.owner_settings_password, name='owner_settings_password'),
    path('owner/dashboard/settings/notifications/', views.owner_settings_notifications, name='owner_settings_notifications'),
    path('owner/dashboard/settings/privacy/', views.owner_settings_privacy, name='owner_settings_privacy'),
    path('owner/dashboard/settings/language/', views.owner_settings_language, name='owner_settings_language'),
    path('owner/dashboard/settings/delete/', views.owner_settings_delete_account, name='owner_settings_delete'),
    path('owner/dashboard/help/', views.owner_help_support, name='owner_help'),

    path('support/quick/', views.quick_support_ticket, name='quick_support_ticket'),

    path('admin/dashboard/', views.admin_home, name='admin'),
    path('super-admin/dashboard/', views.admin_home, name='super_admin'),
    path('admin/dashboard/users/', views.admin_users, name='admin_users'),
    path('admin/dashboard/users/<int:pk>/block/', views.admin_user_set_active, {'active': False}, name='admin_user_block'),
    path('admin/dashboard/users/<int:pk>/unblock/', views.admin_user_set_active, {'active': True}, name='admin_user_unblock'),
    path('admin/dashboard/profile/', views.admin_profile, name='admin_profile'),
    path('admin/dashboard/profile/password/', views.admin_profile_password, name='admin_profile_password'),
    path('admin/dashboard/properties/', views.admin_properties, name='admin_properties'),
    path('admin/dashboard/properties/<int:pk>/', views.admin_property_detail, name='admin_property_detail'),
    path('admin/dashboard/properties/<int:pk>/approve/', views.admin_property_approve, name='admin_property_approve'),
    path('admin/dashboard/properties/<int:pk>/reject/', views.admin_property_reject, name='admin_property_reject'),
    path('admin/dashboard/properties/<int:pk>/status/<str:status>/', views.admin_property_set_status, name='admin_property_set_status'),
    path('admin/dashboard/inquiries/', views.admin_inquiries, name='admin_inquiries'),
    path('admin/dashboard/inquiries/<int:pk>/status/<str:status>/', views.admin_inquiry_set_status, name='admin_inquiry_set_status'),
    path('admin/dashboard/visits/', views.admin_visits, name='admin_visits'),
    path('admin/dashboard/bookings/', views.admin_bookings, name='admin_bookings'),
    path('admin/dashboard/visits/<int:pk>/cancel/', views.admin_visit_cancel, name='admin_visit_cancel'),
    path('admin/dashboard/reviews/', views.admin_reviews, name='admin_reviews'),
    path('admin/dashboard/reviews/<int:pk>/delete/', views.admin_review_delete, name='admin_review_delete'),
    path('admin/dashboard/payments/', views.admin_payments, name='admin_payments'),
    path('admin/dashboard/subscriptions/', views.admin_subscriptions, name='admin_subscriptions'),
    path('admin/dashboard/subscriptions/new/', views.admin_subscription_plan_form, name='admin_subscription_plan_add'),
    path('admin/dashboard/subscriptions/<int:pk>/edit/', views.admin_subscription_plan_form, name='admin_subscription_plan_edit'),
    path('admin/dashboard/subscriptions/<int:pk>/toggle/', views.admin_subscription_plan_toggle, name='admin_subscription_plan_toggle'),
    path('admin/dashboard/reports/', views.admin_reports, name='admin_reports'),
    path('admin/dashboard/support/', views.admin_support, name='admin_support'),
    path('admin/dashboard/support/<int:pk>/status/<str:status>/', views.admin_support_set_status, name='admin_support_set_status'),
    path('admin/dashboard/cms/', views.admin_cms_faqs, name='admin_cms'),
    path('admin/dashboard/cms/new/', views.admin_cms_faq_form, name='admin_cms_faq_add'),
    path('admin/dashboard/cms/<int:pk>/edit/', views.admin_cms_faq_form, name='admin_cms_faq_edit'),
    path('admin/dashboard/cms/<int:pk>/delete/', views.admin_cms_faq_delete, name='admin_cms_faq_delete'),
    path('admin/dashboard/cms/<int:pk>/toggle/', views.admin_cms_faq_toggle, name='admin_cms_faq_toggle'),
    path('admin/dashboard/cms/cities/', views.admin_cities, name='admin_cities'),
    path('admin/dashboard/cms/cities/new/', views.admin_city_form, name='admin_city_add'),
    path('admin/dashboard/cms/cities/<int:pk>/edit/', views.admin_city_form, name='admin_city_edit'),
    path('admin/dashboard/cms/cities/<int:pk>/delete/', views.admin_city_delete, name='admin_city_delete'),
    path('admin/dashboard/cms/cities/<int:pk>/toggle/', views.admin_city_toggle, name='admin_city_toggle'),
    path('admin/dashboard/cms/content-blocks/', views.admin_content_blocks, name='admin_content_blocks'),
    path('admin/dashboard/cms/content-blocks/new/', views.admin_content_block_form, name='admin_content_block_add'),
    path('admin/dashboard/cms/content-blocks/<int:pk>/edit/', views.admin_content_block_form, name='admin_content_block_edit'),
    path('admin/dashboard/cms/content-blocks/<int:pk>/delete/', views.admin_content_block_delete, name='admin_content_block_delete'),
    path('admin/dashboard/cms/content-blocks/<int:pk>/toggle/', views.admin_content_block_toggle, name='admin_content_block_toggle'),
    path('admin/dashboard/cms/legal-pages/', views.admin_legal_pages, name='admin_legal_pages'),
    path('admin/dashboard/cms/legal-pages/<int:pk>/edit/', views.admin_legal_page_form, name='admin_legal_page_edit'),
    path('admin/dashboard/cms/site-settings/', views.admin_site_settings, name='admin_site_settings'),
    path('admin/dashboard/cms/seo/', views.admin_seo_settings, name='admin_seo_settings'),
    path('admin/dashboard/cms/seo/<int:pk>/edit/', views.admin_page_seo_form, name='admin_page_seo_edit'),
    path('admin/dashboard/audit-logs/', views.admin_audit_logs, name='admin_audit_logs'),
    path('admin/dashboard/admin-users/', views.admin_internal_users, name='admin_internal_users'),
    path('admin/dashboard/admin-users/new/', views.admin_user_create, name='admin_user_create'),
    path(
        'admin/dashboard/admin-users/<int:pk>/role/admin/', views.admin_user_set_role,
        {'role': 'admin'}, name='admin_user_set_role_admin',
    ),
    path(
        'admin/dashboard/admin-users/<int:pk>/role/super_admin/', views.admin_user_set_role,
        {'role': 'super_admin'}, name='admin_user_set_role_super_admin',
    ),
    path(
        'admin/dashboard/admin-users/<int:pk>/activate/', views.admin_user_set_active_internal,
        {'active': True}, name='admin_internal_user_activate',
    ),
    path(
        'admin/dashboard/admin-users/<int:pk>/deactivate/', views.admin_user_set_active_internal,
        {'active': False}, name='admin_internal_user_deactivate',
    ),
    path('admin/dashboard/settings/', views.admin_settings, name='admin_settings'),
    path('admin/dashboard/settings/send-test-email/', views.admin_send_test_email, name='admin_send_test_email'),
]
