# Generated by Django 6.0.7 on 2026-08-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='page_url',
            field=models.CharField(blank=True, help_text='Page the user was on when they raised this via the floating help widget.', max_length=255),
        ),
    ]
