# Generated by Django 6.0.7 on 2026-08-29 03:52

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_supportticket_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF, image or document — up to 5 MB.', null=True, upload_to='support_tickets/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'txt']), core.validators.MaxFileSizeValidator(5120)]),
        ),
    ]
