# Generated by Django 6.0.7 on 2026-08-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=300)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/')),
                ('preferred_city', models.CharField(blank=True, max_length=60)),
                ('preferred_budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent_house', 'Independent House'), ('villa', 'Villa'), ('room', 'Room'), ('pg', 'PG Accommodation'), ('shared', 'Shared Accommodation')], max_length=20)),
                ('furnishing_preference', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=20)),
                ('tenant_type', models.CharField(blank=True, choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('professionals', 'Working Professionals'), ('students', 'Students')], max_length=20)),
                ('move_in_time', models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('within_1_month', 'Within 1 Month'), ('within_3_months', 'Within 3 Months'), ('flexible', 'Flexible')], max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('visit_reminders', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('new_property_alerts', models.BooleanField(default=True)),
                ('offers_updates', models.BooleanField(default=False)),
                ('show_profile_to_owners', models.BooleanField(default=True)),
                ('allow_owner_contact', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
