# Generated by Django 6.0.7 on 2026-08-28 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('new_inquiry_alerts', models.BooleanField(default=True)),
                ('visit_reminders', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('offers_updates', models.BooleanField(default=False)),
                ('show_contact_to_tenants', models.BooleanField(default=True)),
                ('allow_tenant_contact', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
