# Generated by Django 6.0.7 on 2026-08-29 03:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', validators=[core.validators.MaxFileSizeValidator(2048)]),
        ),
    ]
