# Generated by Django 6.0.7 on 2026-08-14 13:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(max_length=40)),
                ('group', models.CharField(choices=[('basic', 'Basic'), ('home', 'Home'), ('society', 'Society')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('residential', 'Residential Property'), ('room', 'Room'), ('pg', 'PG Accommodation'), ('shared', 'Shared Accommodation'), ('hotel', 'Hotel'), ('guest_house', 'Guest House'), ('homestay', 'Homestay')], default='residential', max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Flat / Apartment'), ('independent_house', 'Independent House'), ('villa', 'Villa'), ('builder_floor', 'Builder Floor'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('room', 'Room'), ('other', 'Other')], max_length=20)),
                ('furnishing_status', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=20)),
                ('property_age', models.CharField(blank=True, choices=[('under_construction', 'Under Construction'), ('lt_1', 'Less than 1 Year'), ('1_3', '1 - 3 Years'), ('3_5', '3 - 5 Years'), ('5_10', '5 - 10 Years'), ('gt_10', '10+ Years')], max_length=20)),
                ('total_area', models.PositiveIntegerField(blank=True, help_text='sq.ft.', null=True)),
                ('carpet_area', models.PositiveIntegerField(blank=True, help_text='sq.ft.', null=True)),
                ('built_up_area', models.PositiveIntegerField(blank=True, help_text='sq.ft.', null=True)),
                ('facing', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=12)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('balconies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking', models.CharField(blank=True, choices=[('none', 'No Parking'), ('bike', 'Bike Parking'), ('car', 'Car Parking'), ('both', 'Both')], default='none', max_length=10)),
                ('country', models.CharField(default='India', max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('area_locality', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('tenant_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('family', 'Family'), ('bachelor_male', 'Bachelor Male'), ('bachelor_female', 'Bachelor Female'), ('bachelor_couple', 'Bachelor / Couple'), ('students', 'Students'), ('professionals', 'Working Professionals'), ('anyone', 'Anyone')], max_length=20), blank=True, default=list)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('electricity_charges', models.CharField(blank=True, help_text='e.g. "As per meter" or a flat amount', max_length=60)),
                ('water_charges', models.CharField(blank=True, max_length=60)),
                ('no_brokerage', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('minimum_stay', models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('11_months', '11 Months'), ('1_year', '1 Year'), ('flexible', 'Flexible')], max_length=15)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('lease_duration', models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('11_months', '11 Months'), ('1_year', '1 Year'), ('flexible', 'Flexible')], max_length=15)),
                ('contact_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chat', 'Platform Chat'), ('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10), blank=True, default=list)),
                ('listing_plan', models.CharField(choices=[('free', 'Free Listing'), ('silver', 'Silver Listing'), ('gold', 'Gold Listing'), ('premium', 'Premium Listing')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('paused', 'Paused'), ('rented', 'Rented'), ('archived', 'Archived')], default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=60)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
