# Generated by Django 6.0.7 on 2026-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-night rate for Hotel / Guest House / Homestay listings — used for real bookings.', max_digits=10, null=True),
        ),
    ]
