# Generated by Django 6.0.7 on 2026-08-29 03:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_nightly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='image',
            field=models.ImageField(upload_to='properties/%Y/%m/', validators=[core.validators.MaxFileSizeValidator(30)]),
        ),
    ]
